# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 07:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Created_time',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('external_id', models.IntegerField(max_length=10)),
                ('memberid', models.IntegerField(max_length=10)),
                ('created_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Onethink_branchstyle',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('partyid', models.IntegerField(max_length=10)),
                ('partyname', models.CharField(max_length=255)),
                ('lovesum', models.IntegerField(max_length=10)),
                ('messagesum', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Onethink_comment',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('start_time', models.IntegerField(max_length=10)),
                ('end_time', models.IntegerField(max_length=10)),
                ('partyid', models.IntegerField(max_length=10)),
                ('releasestate', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Onethink_commentobj',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('external_id', models.IntegerField(max_length=10)),
                ('memberid', models.IntegerField(max_length=10)),
                ('membername', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Onethink_commentrec',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('external_id', models.IntegerField(max_length=10)),
                ('performance', models.CharField(max_length=50)),
                ('memberid', models.IntegerField(max_length=10)),
                ('membername', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Onethink_company',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('info', models.TextField(verbose_name='企业名字')),
                ('type', models.CharField(max_length=255)),
                ('scope', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('linkman', models.CharField(max_length=255)),
                ('weixin', models.ImageField(upload_to='')),
                ('contact', models.CharField(max_length=255)),
                ('partyid', models.IntegerField(max_length=10)),
                ('partyname', models.CharField(max_length=255)),
                ('releasestate', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Onethink_excellent',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('story', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('author', models.CharField(max_length=30)),
                ('time', models.IntegerField(max_length=10)),
                ('partyid', models.IntegerField(max_length=10)),
                ('releasestate', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Onethink_goods',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('info', models.TextField(verbose_name='产品介绍')),
                ('price', models.IntegerField(max_length=10)),
                ('companyid', models.IntegerField(max_length=10)),
                ('companyname', models.CharField(max_length=255)),
                ('partyid', models.IntegerField(max_length=10)),
                ('releasestate', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Onethink_information',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('activity_info', models.TextField()),
                ('author', models.CharField(max_length=30)),
                ('attend_num', models.IntegerField(max_length=10)),
                ('partyid', models.IntegerField(max_length=10)),
                ('time', models.IntegerField(max_length=10)),
                ('releasestate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Onethink_membermessage',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('memberid', models.IntegerField(max_length=10)),
                ('membername', models.CharField(max_length=255)),
                ('message', models.TextField(verbose_name='留言')),
                ('time', models.IntegerField(max_length=10)),
                ('status', models.IntegerField(max_length=2)),
                ('partyid', models.IntegerField(max_length=10)),
                ('memberstyleid', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Onethink_memberstyle',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('memberid', models.IntegerField(max_length=10)),
                ('membername', models.CharField(max_length=255)),
                ('info', models.TextField(verbose_name='个人简介')),
                ('lovesum', models.IntegerField(max_length=10)),
                ('discuss', models.IntegerField(max_length=10)),
                ('releasestate', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Onethink_mobileclassroom',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('type', models.IntegerField(max_length=10)),
                ('topic', models.CharField(max_length=255)),
                ('releasestate', models.IntegerField(max_length=2)),
                ('author', models.CharField(max_length=30)),
                ('time', models.IntegerField(max_length=10)),
                ('partyid', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Onethink_partyactivities',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255, verbose_name='活动主题')),
                ('activity_info', models.TextField()),
                ('author', models.CharField(max_length=30)),
                ('attend_num', models.IntegerField(max_length=10)),
                ('partyid', models.IntegerField(max_length=10)),
                ('time', models.IntegerField(max_length=10)),
                ('releasestate', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Onethink_partycharge',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('memberid', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('partyid', models.IntegerField(max_length=10)),
                ('salary', models.IntegerField(max_length=10)),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('charge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('month', models.IntegerField(max_length=7)),
                ('status', models.IntegerField(max_length=2)),
                ('releasesta', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Onethink_partygroup',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('partyname', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='../static/img')),
                ('partydesc', models.TextField(max_length=500)),
                ('company', models.CharField(max_length=150)),
                ('contacter', models.CharField(max_length=30)),
                ('releasesta', models.IntegerField(default=1)),
                ('manager_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Onethink_partymember',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=60, verbose_name='党内职务')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('partyid', models.IntegerField(default=1)),
                ('partyname', models.CharField(max_length=150)),
                ('joindate', models.IntegerField(max_length=10)),
                ('memberage', models.IntegerField(default=0, max_length=10)),
                ('mobilephon', models.IntegerField(max_length=13)),
                ('releasesta', models.IntegerField(default=1, verbose_name='发布状态')),
                ('mail', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Onethink_partymessage',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('memberid', models.IntegerField(max_length=10)),
                ('membername', models.CharField(max_length=255)),
                ('message', models.TextField(verbose_name='留言内容')),
                ('time', models.IntegerField(max_length=10)),
                ('status', models.IntegerField(max_length=2)),
                ('partyid', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Onethink_partyrequest',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('requestname', models.CharField(max_length=30)),
                ('cardid', models.CharField(max_length=19)),
                ('mobilephone', models.IntegerField(max_length=12)),
                ('introducer', models.CharField(max_length=30)),
                ('partyid', models.IntegerField(max_length=10)),
                ('partyname', models.CharField(max_length=150)),
                ('requestinfo', models.TextField()),
                ('time', models.DateTimeField(max_length=10)),
                ('releasestate', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Onethink_performance',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('memberid', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('partyid', models.IntegerField(default=1, max_length=10)),
                ('month', models.IntegerField(max_length=7)),
                ('performance', models.CharField(default=1, max_length=50)),
                ('releasestate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Onethink_recruit',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=255)),
                ('jobrequire', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('companyid', models.IntegerField(max_length=10)),
                ('companyname', models.CharField(max_length=255)),
                ('partyid', models.IntegerField(max_length=10)),
                ('releasestate', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Onethink_volunteer',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('activity_info', models.TextField()),
                ('author', models.CharField(max_length=30)),
                ('attend_num', models.IntegerField(max_length=10)),
                ('partyid', models.IntegerField(max_length=10)),
                ('time', models.IntegerField(max_length=10)),
                ('releasestate', models.IntegerField(default='0')),
            ],
        ),
        migrations.DeleteModel(
            name='Branch_manager',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
