# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test', '0003_auto_20180315_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onethink_performance',
            name='memberid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='onethink_performance',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='onethink_performance',
            name='partyid',
            field=models.IntegerField(default=1),
        ),
    ]
