# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test', '0004_auto_20180315_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onethink_partygroup',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
