# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test', '0005_auto_20180316_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onethink_mobileclassroom',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
